//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVcompanyWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AVcompanydbEntities : DbContext
    {
        public AVcompanydbEntities()
            : base("name=AVcompanydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<PriceProduct> PriceProducts { get; set; }
        public virtual DbSet<PriceType> PriceTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<WoodProtectionType> WoodProtectionTypes { get; set; }
        public virtual DbSet<WoodType> WoodTypes { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
    }
}
