//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVcompanyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public int customerId { get; set; }
        public string firstName { get; set; }
        public string LastName { get; set; }
        public string dni { get; set; }
        public string numberPhone { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
