//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVcompanyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PriceProducts = new HashSet<PriceProduct>();
            this.Uploads = new HashSet<Upload>();
        }
    
        public int id { get; set; }
        public Nullable<int> woodTypeId { get; set; }
        public Nullable<int> subCategoryId { get; set; }
        public Nullable<int> woodProtectionTypeId { get; set; }
        public string identifierCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<double> manufacturingTime { get; set; }
        public Nullable<bool> isExclusive { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceProduct> PriceProducts { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual WoodProtectionType WoodProtectionType { get; set; }
        public virtual WoodType WoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Upload> Uploads { get; set; }
    }
}
