//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVcompanyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public string name { get; set; }
        public string locationPath { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string srcImage { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
